# Generated by Django 5.2.7 on 2025-11-15 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_food_tag_recipe_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food_tag',
            new_name='FoodTag',
        ),
    ]
